In [2]:
import pandas as pd

In [26]:
df_crimes = pd.read_csv("data/crimes.csv")
df_crimes

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13708839,JJ101083,01/01/2025 11:59:00 PM,009XX N CICERO AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,CTA BUS,True,False,...,37,25,14,1144183.0,1906031.0,2025,05/17/2025 03:40:52 PM,41.898171,-87.745876,"(41.89817106, -87.74587608)"
1,13726091,JJ121235,01/01/2025 11:50:00 PM,035XX W Cortland St,0710,THEFT,THEFT FROM MOTOR VEHICLE,STREET,False,False,...,26,22,06,1152731.0,1912404.0,2025,11/02/2025 03:41:09 PM,41.915494,-87.714311,"(41.915494255, -87.714310832)"
2,13709367,JJ101705,01/01/2025 11:47:00 PM,072XX S HOYNE AVE,2820,OTHER OFFENSE,TELEPHONE THREAT,RESIDENCE,False,False,...,17,67,08A,1163613.0,1856698.0,2025,11/02/2025 03:41:09 PM,41.762409,-87.675898,"(41.7624087, -87.675897826)"
3,13708888,JJ101098,01/01/2025 11:45:00 PM,013XX W 76TH ST,0430,BATTERY,AGGRAVATED - OTHER DANGEROUS WEAPON,APARTMENT,False,False,...,17,71,04B,1168743.0,1854387.0,2025,05/17/2025 03:40:52 PM,41.755958,-87.657162,"(41.755957881, -87.657162192)"
4,13708933,JJ101118,01/01/2025 11:39:00 PM,005XX W OAK ST,1710,OFFENSE INVOLVING CHILDREN,ENDANGERING LIFE / HEALTH OF CHILD,APARTMENT,False,True,...,27,8,20,1172329.0,1907062.0,2025,05/17/2025 03:40:52 PM,41.900425,-87.642468,"(41.900424796, -87.642467932)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259642,13325219,JH100510,01/01/2024 12:00:00 AM,059XX W LAKE ST,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,True,...,29,25,14,1136680.0,1902267.0,2024,12/21/2024 03:40:46 PM,41.887980,-87.773525,"(41.887979835, -87.773524594)"
259643,13326167,JH101437,01/01/2024 12:00:00 AM,040XX S DREXEL BLVD,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,4,36,14,1182780.0,1878176.0,2024,12/21/2024 03:40:46 PM,41.820923,-87.604982,"(41.820922725, -87.604981565)"
259644,13325994,JH101383,01/01/2024 12:00:00 AM,036XX S WOLCOTT AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,12,59,06,1164283.0,1880493.0,2024,12/21/2024 03:40:46 PM,41.827691,-87.672772,"(41.827691054, -87.672772029)"
259645,13325509,JH100882,01/01/2024 12:00:00 AM,082XX S ELIZABETH ST,1477,WEAPONS VIOLATION,RECKLESS FIREARM DISCHARGE,RESIDENCE,False,False,...,17,71,15,1169426.0,1850104.0,2024,12/21/2024 03:40:46 PM,41.744190,-87.654783,"(41.744189992, -87.654782936)"
259646,13325146,JH100483,01/01/2024 12:00:00 AM,077XX S LUELLA AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,7,43,14,1192545.0,1854061.0,2024,12/21/2024 03:40:46 PM,41.754517,-87.569945,"(41.754516844, -87.569944944)"

In [28]:
df_crimes["Latitude"].isna().sum()

1264

In [29]:
df_crimes.dtypes

ID                        int64
Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                  int64
Ward                      int64
Community Area            int64
FBI Code                 object
X Coordinate            float64
Y Coordinate            float64
Year                      int64
Updated On               object
Latitude                float64
Longitude               float64
Location                 object
dtype: object

In [ ]:
df_crimes = df_crimes.drop(["Case Number", "Block", "IUCR", "Domestic", "Beat", "District", "Ward", "Community Area", "FBI Code", "X Coordinate", "Y Coordinate"], axis=1)

In [ ]:
df_crimes = df_crimes[(df_crimes["Latitude"].isna() == False) & (df_crimes["Longitude"].isna() == False)]

In [46]:
df_crimes.dtypes

ID                        int64
Date                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Year                      int64
Updated On               object
Latitude                float64
Longitude               float64
Location                 object
dtype: object

In [40]:
df_libraries = pd.read_csv("data/libraries.csv")
df_libraries

,BRANCH,SERVICE HOURS,ADDRESS,CITY,STATE,ZIP,PHONE,WEBSITE,BRANCH EMAIL,LOCATION
0,Albany Park,"Mon. & Wed., 10-6; Tues. & Thurs., Noon-8; Fri...",3401 W. Foster Ave.,Chicago,IL,60625,(773) 539-5450,https://www.chipublib.org/locations/3/,albanypark@chipublib.org,"(41.97557881655979, -87.71361314512697)"
1,Altgeld,"Mon. & Wed., Noon-8; Tue. & Thu., 10-6; Fri. &...",955 E. 131st St.,Chicago,IL,60827,(312) 747-3270,https://www.chipublib.org/locations/4/,altgeld@chipublib.org,"(41.65719847558056, -87.59883829075173)"
2,Archer Heights,"Mon. & Wed., Noon-8; Tue. & Thu., 10-6; Fri. &...",5055 S. Archer Ave.,Chicago,IL,60632,(312) 747-9241,https://www.chipublib.org/locations/5/,archerheights@chipublib.org,"(41.80110836194246, -87.72648385568911)"
3,Austin,"Mon. & Wed., Noon-8; Tues. & Thurs., 10-6; Fri...",5615 W. Race Ave.,Chicago,IL,60644,(312) 746-5038,https://www.chipublib.org/locations/6/,austin@chipublib.org,"(41.88917312206642, -87.7658203582574)"
4,Austin-Irving,"Mon. & Wed., Noon-8; Tue. & Thu., 10-6; Fri. &...",6100 W. Irving Park Rd.,Chicago,IL,60634,(312) 744-6222,https://www.chipublib.org/locations/7/,austin-irving@chipublib.org,"(41.95312267684315, -87.77928489355646)"
...,...,...,...,...,...,...,...,...,...,...
76,West Pullman,"Mon. & Wed., Noon-8; Tue. & Thu., 10-6; Fri. &...",830 W. 119th St.,Chicago,IL,60643,(312) 747-1425,https://www.chipublib.org/locations/78/,westpullman@chipublib.org,"(41.67790647382097, -87.6431683153105)"
77,West Town,"Mon. & Wed., 10-6; Tues. & Thurs., Noon-8; Fri...",1625 W. Chicago Ave.,Chicago,IL,60622,(312) 743-0450,https://www.chipublib.org/locations/79/,westtown@chipublib.org,"(41.89594730478282, -87.66829305460979)"
78,"Whitney M. Young, Jr.","Mon. & Wed., 10-6; Tues. & Thurs., Noon-8; Fri...",415 East 79th St.,Chicago,IL,60619,(312) 747-0039,https://www.chipublib.org/locations/80/,whitneyyoung@chipublib.org,"(41.7510184591363, -87.61495065361933)"
79,Woodson Regional Library,"Mon. - Thurs., 9-8; Fri. & Sat., 9-5; Sun., 1-5",9525 S. Halsted St.,Chicago,IL,60628,(312) 747-6900,https://www.chipublib.org/locations/81/,woodsonregional@chipublib.org,"(41.720694885749005, -87.64304817213312)"
80,Wrightwood-Ashburn,"Mon. & Wed., Noon-8; Tue. & Thu., 10-6; Fri. &...",8530 S. Kedzie Ave.,Chicago,IL,60652,(312) 747-2696,https://www.chipublib.org/locations/82/,wrightwood-ashburn@chipublib.org,"(41.73795704970435, -87.70221598421591)"

In [41]:
df_libraries["LOCATION"].isna().sum()

0

In [ ]:
df_libraries = df_libraries.drop(["PHONE", "WEBSITE", "BRANCH EMAIL"], axis=1)

In [47]:
df_libraries[['LATITUDE', 'LONGITUDE']] = (df_libraries['LOCATION'].str.replace('[()]', '', regex=True).str.split(',', expand=True))
df_libraries = df_libraries.assign(LATITUDE=df_libraries['LATITUDE'].astype(float),LONGITUDE=df_libraries['LONGITUDE'].astype(float))

In [49]:
df_libraries.dtypes

BRANCH            object
SERVICE HOURS     object
ADDRESS           object
CITY              object
STATE             object
ZIP                int64
LOCATION          object
LATITUDE         float64
LONGITUDE        float64
dtype: object

In [5]:
df_parks = pd.read_csv("data/parks.csv")
df_parks

,the_geom,OBJECTID_1,PARK,PARK_NO,FACILITY_N,FACILITY_T,X_COORD,Y_COORD,GISOBJID
0,POINT (-87.63769762610757 41.76299921150787),1,HAMILTON (ALEXANDER),9,CULTURAL CENTER,SPECIAL,-87.637698,41.762999,"2,494"
1,POINT (-87.63792902986378 41.76281652413111),2,HAMILTON (ALEXANDER),9,GYMNASIUM,INDOOR,-87.637929,41.762817,"2,495"
2,POINT (-87.63691359952075 41.76084939012162),3,HAMILTON (ALEXANDER),9,BASEBALL JR/SOFTBALL,OUTDOOR,-87.636914,41.760849,"2,496"
3,POINT (-87.63832013450008 41.76200535623585),4,HAMILTON (ALEXANDER),9,BASEBALL JR/SOFTBALL,OUTDOOR,-87.638320,41.762005,"2,497"
4,POINT (-87.63805916836576 41.76047384589964),5,HAMILTON (ALEXANDER),9,BASEBALL JR/SOFTBALL,OUTDOOR,-87.638059,41.760474,"2,498"
...,...,...,...,...,...,...,...,...,...
4462,POINT (-87.73510131337964 41.80345358991431),"4,507",ARCHER (WILLIAM BEATTY),250,TEEN CENTER,INDOOR,-87.735101,41.803454,"6,794"
4463,POINT (-87.63766614078884 41.762803879346286),"4,508",HAMILTON (ALEXANDER),9,TEEN CENTER,INDOOR,-87.637666,41.762804,"6,793"
4464,POINT (-87.75071605094674 41.77673930365681),"4,509",LAWLER (MICHAEL),"1,011",ART TURF - REGULATION,OUTDOOR,-87.750716,41.776739,"6,806"
4465,POINT (-87.5855355052113 41.78213362866772),"4,510",JACKSON (ANDREW),19,TRACK,OUTDOOR,-87.585536,41.782134,"6,810"
4466,POINT (-87.58535895385735 41.78196370701343),"4,511",JACKSON (ANDREW),19,ARTIFICIAL TURF REG,OUTDOOR,-87.585359,41.781964,"6,809"

In [51]:
df_parks = df_parks.drop(["the_geom","GISOBJID"], axis=1)

In [56]:
df_parks.rename(columns={"X_COORD":"LATITUDE","Y_COORD":"LONGITUDE"}, inplace=True)

In [57]:
df_parks.dtypes

OBJECTID_1     object
PARK           object
PARK_NO        object
FACILITY_N     object
FACILITY_T     object
LATITUDE      float64
LONGITUDE     float64
dtype: object

In [11]:
df_affordable_housing = pd.read_excel("data/affordable_housing.xlsx", nrows=79, header=3)
df_affordable_housing

,Area,Total Units,Total Affordable,Total Legally Restricted,Total NOAH,Total Higher Rent,Total No Rent,% Affordable,% Legally Restricted,% NOAH,...,Total Legally Restricted.2,Total NOAH.2,Total Higher Rent.2,Total No Rent.2,Total Units.3,Total Affordable.3,Total Legally Restricted.3,Total NOAH.3,Total Higher Rent.3,Total No Rent.3
0,ALBANY PARK,9825.0,3052.0,340.0,2712.0,6600.0,173.0,0.310636,0.034606,0.276031,...,57.0,1562.0,2611.0,63.0,2263.0,446.0,51.0,395.0,1744.0,73.0
1,ARCHER HEIGHTS,1788.0,1028.0,4.0,1024.0,681.0,79.0,0.574944,0.002237,0.572707,...,2.0,563.0,215.0,30.0,770.0,306.0,2.0,304.0,415.0,49.0
2,ARMOUR SQUARE,3274.0,2179.0,874.0,1305.0,977.0,118.0,0.665547,0.266952,0.398595,...,240.0,689.0,309.0,17.0,742.0,302.0,114.0,188.0,339.0,101.0
3,ASHBURN,2036.0,892.0,90.0,802.0,1135.0,9.0,0.438114,0.044204,0.393910,...,18.0,499.0,196.0,0.0,1057.0,194.0,4.0,190.0,863.0,0.0
4,AUBURN GRESHAM,9722.0,5798.0,1181.0,4617.0,3651.0,273.0,0.596379,0.121477,0.474902,...,299.0,2659.0,855.0,99.0,2927.0,983.0,149.0,834.0,1805.0,139.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,WEST RIDGE,13456.0,3142.0,595.0,2547.0,10061.0,253.0,0.233502,0.044218,0.189284,...,100.0,1467.0,3825.0,101.0,3134.0,368.0,22.0,346.0,2716.0,50.0
75,WEST TOWN,22638.0,4581.0,1809.0,2772.0,17396.0,661.0,0.202359,0.079910,0.122449,...,207.0,1808.0,8770.0,263.0,5243.0,986.0,694.0,292.0,3929.0,328.0
76,WOODLAWN,8019.0,3801.0,2251.0,1550.0,3968.0,250.0,0.473999,0.280708,0.193291,...,812.0,325.0,1184.0,54.0,2785.0,982.0,324.0,658.0,1663.0,140.0
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,CITY OF CHICAGO,580202.0,209427.0,59269.0,150158.0,355738.0,15037.0,0.360955,0.102152,0.258803,...,17308.0,76464.0,111495.0,5668.0,136895.0,43258.0,10607.0,32651.0,87642.0,5995.0

In [58]:
df_affordable_housing.dtypes

Area                           object
Total Units                   float64
Total Affordable              float64
Total Legally Restricted      float64
Total NOAH                    float64
Total Higher Rent             float64
Total No Rent                 float64
% Affordable                  float64
% Legally Restricted          float64
% NOAH                        float64
Total Units.1                 float64
Total Affordable.1            float64
Total Legally Restricted.1    float64
Total NOAH.1                  float64
Total Higher Rent.1           float64
Total No Rent.1               float64
Total Units.2                 float64
Total Affordable.2            float64
Total Legally Restricted.2    float64
Total NOAH.2                  float64
Total Higher Rent.2           float64
Total No Rent.2               float64
Total Units.3                 float64
Total Affordable.3            float64
Total Legally Restricted.3    float64
Total NOAH.3                  float64
Total Higher Rent.3           float64
Total No Rent.3               float64
dtype: object

In [12]:
df_neighborhoods = pd.read_csv("data/neighborhoods.csv")
df_neighborhoods

,the_geom,PRI_NEIGH,SEC_NEIGH,SHAPE_AREA,SHAPE_LEN
0,MULTIPOLYGON (((-87.60670812560372 41.81681377...,Grand Boulevard,BRONZEVILLE,"48,492,503.1554","28,196.837157"
1,MULTIPOLYGON (((-87.62760697485348 41.87437097...,Printers Row,PRINTERS ROW,"2,162,137.97139","6,864.247156"
2,MULTIPOLYGON (((-87.66706868914602 41.88885187...,United Center,UNITED CENTER,"32,520,512.7053","23,101.363745"
3,MULTIPOLYGON (((-87.65833494805533 41.92166144...,Sheffield & DePaul,SHEFFIELD & DEPAUL,"10,482,592.2987","13,227.049745"
4,MULTIPOLYGON (((-87.74059567509266 41.88782316...,Humboldt Park,HUMBOLDT PARK,"125,010,425.593","46,126.751351"
...,...,...,...,...,...
93,MULTIPOLYGON (((-87.74142999502229 41.91698483...,Belmont Cragin,"BELMONT CRAGIN,HERMOSA","109,099,407.211","43,311.706886"
94,MULTIPOLYGON (((-87.75619515209075 41.91546954...,Austin,AUSTIN,"170,037,750.826","55,473.345911"
95,MULTIPOLYGON (((-87.62645810267597 41.91147052...,Gold Coast,GOLD COAST,"7,165,705.53467","13,685.479377"
96,MULTIPOLYGON (((-87.64878470805166 41.93998753...,Boystown,BOYSTOWN,"3,365,778.97115","9,780.268985"
97,MULTIPOLYGON (((-87.63144510787805 41.90390085...,River North,RIVER NORTH,"38,766,442.5194","31,506.03781"